
name: Test Automation Workflow

on:
  schedule:
  - cron: 00 18 * * *
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Running Test Automation Framework with Maven
      run: mvn test -X -Dbrowser=chrome -DisLambdaTest=true -DisHeadLess=false
      
    - name: Upload Test Logs
      if: always()
      uses: actions/upload-artifact@v4.6.2
      with:
       name: Test logs
       path: logs/

    - name: Upload Screenshots as Artifacts
      if: always()
      uses: actions/upload-artifact@v4.6.2
      with:
       name: screenshots
       path: creenshots/

    - name: Upload Test Report
      if: always()
      uses: actions/upload-artifact@v4.6.2
      with:
       name: Test reports
       path: report.html
       
    - name: Test Execution Status
      if: always()
      run: echo "Test Execution Completed"

    -name: Copy Report to gh-pages Folder
    if: always()
     
     run:
       mkdir -p public/extend-reports/
       cp- -R screenshots/ public/extend-reports/screenshots/
       Is -1

       -name: Deploy
       if: always()
       uses: JamesIves/github-pages-deploy-action@v4
       with:
         folder: public/extend-reports/
         token: ${{ secrets.PAT}}
         clean: true

      
       
  
    
